function specs = banbura2008ModelSpecifications()
%BANBURA2008MODELSPECIFICATIONS Variable panels from "Large Bayesian VARs".
%   SPECS = BANBURA2008MODELSPECIFICATIONS() returns the SMALL, CEE,
%   MEDIUM and LARGE model definitions used by Banbura, Giannone and
%   Reichlin (2008). The listed order is the recursive structural order:
%   slow-moving variables, the federal funds rate, then fast-moving
%   financial variables.
%
%   See also MINNESOTABVARM.

specs = struct();

specs.SMALL = localSpec( ...
    "SMALL", ...
    ["EMPL" "CPI" "FFR"], ...
    "FFR", ...
    3, ...
    Inf);

specs.CEE = localSpec( ...
    "CEE", ...
    ["EMPL" "CPI" "COMM_PR" "FFR" "NBORR_RES" "TOT_RES" "M2"], ...
    "FFR", ...
    7, ...
    0.262);

specs.MEDIUM = localSpec( ...
    "MEDIUM", ...
    ["EMPL" "CPI" "COMM_PR" "INCOME" "CONSUM" "IP" "CAP_UTIL" ...
     "UNEMPL" "HOUS_START" "PPI" "PCE_DEFL" "HOUR_EARN" "FFR" ...
     "M1" "M2" "TOT_RES" "NBORR_RES" "SP" "TB_YIELD" "EXR"], ...
    "FFR", ...
    20, ...
    0.108);

specs.LARGE = localSpec( ...
    "LARGE", ...
    strings(1,0), ...
    "FFR", ...
    131, ...
    0.035);

end

function spec = localSpec(name, variables, policyVariable, requiredVariableCount, lambda)
spec = struct();
spec.Name = name;
spec.Variables = variables;
spec.PolicyVariable = policyVariable;
spec.PolicyIndex = find(variables == policyVariable, 1);
spec.RequiredVariableCount = requiredVariableCount;
spec.lambda1 = lambda;
spec.lambda4 = 10*lambda;
if isinf(lambda)
    spec.lambda4 = Inf;
end
end
